.gitignore
workshops/kfp-caip-sklearn/lab-01-caip-containers/exercises/lab-01.ipynb
workshops/kfp-caip-sklearn/lab-01-caip-containers/lab-01.ipynb

In lab-01-caip-containers:
- added learning objectives
- moved the licensing at the end of the notebook
- added an exercise folder with a notebook with exercises

lab-01-caip-containers: Learning objectives and exercises

---

examples/mlops-env-on-gcp/README.md
examples/mlops-env-on-gcp/creating-notebook-instance/README.md
examples/mlops-env-on-gcp/provisioning-kfp/README.md

- Update repo link in instructions
- Fix typos
- Add documentation links and formatting for readability

Small fixes and additions to mlops-env-on-gcp labs.

---

workshops/tfx-caip-tf21/install.sh
workshops/tfx-caip-tf21/lab-02-tfx-pipeline/exercises/lab-02.ipynb
workshops/tfx-caip-tf21/lab-02-tfx-pipeline/pipeline/config.py

- Add formatted lab-02-tfx-pipeline exercise notebook.
- Update packages and config defaults:
TFX -> 0.21.4
KFP -> 0.5.1
skaffold -> latest

Add lab-02-tfx-pipeline exercises.

---

model_serving/bqml-caip/README.md
model_serving/bqml-caip/bqml-to-caip-pipeline.ipynb

Requesting to add content:
Under model_serving, add folder bqml-caip.  In folder, add one notebook.

Add BQML Export to CAIP Prediction

---

model_serving/bqml-caip/01-bqml-to-caip-tutorial.ipynb
model_serving/bqml-caip/02-bqml-to-caip-pipeline.ipynb
model_serving/bqml-caip/README.md

Added tutorial notebook 01-bqml-to-caip-tutorial.ipynb.
Renamed existing notebook bqml-to-caip-pipeline.ipynb to 02-bqml-to-caip-pipeline.ipynb.
Updated README.md.

Updated files.

---

workshops/tfx-caip-tf21/lab-01-tfx-walkthrough/lab-01.ipynb

- Mirror formatting of notebooks between /exercises + instructor lab folders
- Add additional explanatory text and setup in lab-01 notebook

Update TFX lab-01 instructor lab formatting and instructions.

---

workshops/kfp-caip-sklearn/lab-01-caip-containers/exercises/lab-01.ipynb
workshops/kfp-caip-sklearn/lab-01-caip-containers/lab-01.ipynb

- Modified the code block for model and version creation in 'lab-01.ipynb' notebook

Updated notebook 'lab-01.ipynb'

---

workshops/kfp-caip-sklearn/lab-02-kfp-pipeline/exercises/lab-02.ipynb
workshops/kfp-caip-sklearn/lab-02-kfp-pipeline/lab-02.ipynb

- Added instructions to ignore the incompatibility errors.
- Updated the `ARTIFACT_STORE` bucket name.
- Updated the notebook instructions as per end user's perspective.
- Related buganizer: http://b/176468664

Notebook: lab-02.ipynb-fix

---

workshops/kfp-caip-sklearn/lab-01-caip-containers/exercises/lab-01.ipynb
workshops/kfp-caip-sklearn/lab-01-caip-containers/lab-01.ipynb

Updated the ARTIFACT_STORE bucket name.
Updated the model and version creation commands in notebook.
Related buganizer: http://b/174313462

Notebook: lab-01.ipynb fix 

---

workshops/tfx-caip-tf23/lab-04-tfx-metadata/labs/lab-04.ipynb
workshops/tfx-caip-tf23/lab-04-tfx-metadata/solutions/lab-04.ipynb

- Add instruction for learners to wait for pipeline run to complete before querying metadata.

Quick lab-04 instruction add.

---

workshops/tfx-caip-tf23/lab-02-tfx-pipeline/labs/lab-02.ipynb
workshops/tfx-caip-tf23/lab-02-tfx-pipeline/solutions/lab-02.ipynb

Updated instructions for setting variable for custom service account.

Notebook: lab-02.ipynb-fixes

---

workshops/tfx-caip-tf23/lab-04-tfx-metadata/labs/lab-04.ipynb
workshops/tfx-caip-tf23/lab-04-tfx-metadata/solutions/lab-04.ipynb

Updated instructions for setting variable of custom service account.

Notebook: lab-04.ipynb-fixes

---

workshops/tfx-caip-tf23/lab-03-tfx-cicd/labs/lab-03.ipynb
workshops/tfx-caip-tf23/lab-03-tfx-cicd/solutions/lab-03.ipynb

Updated instruction for setting custom service account variable

Notebook: lab-03.ipynb - fixes

---

workshops/tfx-caip-tf23/README.md
workshops/tfx-caip-tf23/lab-02-tfx-pipeline/labs/lab-02.ipynb
workshops/tfx-caip-tf23/lab-02-tfx-pipeline/solutions/lab-02.ipynb

- Update tuning flag for first exercise for lab-02
- Update outdated README instructions for custom service account

lab-02 exercise + README outdated instruction updates

---

workshops/tfx-caip-tf23/lab-04-tfx-metadata/labs/lab-04.ipynb
workshops/tfx-caip-tf23/lab-04-tfx-metadata/solutions/lab-04.ipynb

TFX lab-04
- Fixes for anomaly artifact paths to point at train & eval split artifacts
- Added in example on retrieving Tuner best_hyperparameters artifact to print search space and best search hparams from latest pipeline run.

TFX lab-04 fixes for anomaly artifact paths, add in retrieve best hparams example.

---

continuous_training/kubeflow/labs/multiple_frameworks_lab.ipynb
continuous_training/kubeflow/solutions/multiple_frameworks_kubeflow.ipynb

1. Added cells in notebook creating following directories:
- scikit_trainer_image
- tensorflow_trainer_image
- pytorch_trainer_image
- xgboost_trainer_image
- pipeline
2. Removed line "test_query=TEST_QUERY," from census_training_pipeline.py file.
3. Minor formatting updates.

Notebook: multiple_frameworks_lab.ipynb fix

---

on_demand/tfx-caip/lab-02-tfx-pipeline/labs/pipeline/model.py
on_demand/tfx-caip/lab-02-tfx-pipeline/solutions/pipeline/model.py
on_demand/tfx-caip/lab-03-tfx-cicd/labs/pipeline/model.py
on_demand/tfx-caip/lab-03-tfx-cicd/solutions/pipeline/model.py
on_demand/tfx-caip/lab-04-tfx-metadata/labs/pipeline/model.py
on_demand/tfx-caip/lab-04-tfx-metadata/solutions/pipeline/model.py
workshops/tfx-caip-tf23/lab-02-tfx-pipeline/labs/pipeline/model.py
workshops/tfx-caip-tf23/lab-02-tfx-pipeline/solutions/pipeline/model.py
workshops/tfx-caip-tf23/lab-03-tfx-cicd/labs/pipeline/model.py
workshops/tfx-caip-tf23/lab-03-tfx-cicd/solutions/pipeline/model.py
workshops/tfx-caip-tf23/lab-04-tfx-metadata/labs/pipeline/model.py
workshops/tfx-caip-tf23/lab-04-tfx-metadata/solutions/pipeline/model.py

Update to TFX labs across workshops and on-demand.
CloudTuner needed to read PROJECT_ID and REGION from environment variables to kick off CAIP Vizier tuning job. These were set in config.py with default values and overridden by learners in notebook. Due to way pipeline code compiled and run with environment variables, CloudTuner always fell back to default values instead of picking up learner values and would fail during pipeline run. To resolve, this PR has CloudTuner read from cloud_ai_platform_args dict during runtime for these values instead, resolving the issue in testing.

TFX labs fix: update Tuner to read fnArgs for runtime GCP args in cloud_ai_platform_args.

---

continuous_training/composer-mlflow/multi_model_trainer.ipynb

Add more and correct code explanations to be aligned with the tutorial.

Better code comments and explanations for Composer tutorial.

---

workshops/kfp-caip-sklearn/lab-01-caip-containers/exercises/lab-01.ipynb
workshops/kfp-caip-sklearn/lab-01-caip-containers/lab-01.ipynb
workshops/kfp-caip-sklearn/lab-02-kfp-pipeline/exercises/lab-02.ipynb
workshops/kfp-caip-sklearn/lab-02-kfp-pipeline/lab-02.ipynb

Hi Benoit, Updated some instructions and added some comments in both target and solution notebooks for lab-01.ipynb and lab-02.ipynb. Thanks for your review.

Added new instructions

---

workshops/kfp-caip-sklearn/lab-01-caip-containers/exercises/lab-01.ipynb
workshops/kfp-caip-sklearn/lab-01-caip-containers/lab-01.ipynb

- Updated an instruction in the solution and target lab notebooks as required.
- Reference buganizer: http://b/182307986

Notebook_Update: lab-01.ipynb

---

workshops/kfp-caip-sklearn/lab-01-caip-containers/exercises/lab-01.ipynb
workshops/kfp-caip-sklearn/lab-01-caip-containers/lab-01.ipynb

- Updated the target & solution notebook - [transfered BQ steps from terminal into CAIP]
- Reference buganizer: http://b/183459786

Notebook_update: lab-01.ipynb (Using custom containers with AI Platform Training)

---

workshops/kfp-caip-sklearn/lab-01-caip-containers/exercises/lab-01.ipynb
workshops/kfp-caip-sklearn/lab-01-caip-containers/lab-01.ipynb

- Updated the instructions in the notebook as required.
- Reference buganizer: http://b/183459786

Notebook_update: lab01.ipynb [Using custom containers with AI Platform Training]

---

on_demand/kfp-caip-sklearn/lab-01-caip-containers/exercises/lab-01.ipynb
on_demand/kfp-caip-sklearn/lab-01-caip-containers/lab-01.ipynb
workshops/kfp-caip-sklearn/lab-01-caip-containers/exercises/lab-01.ipynb
workshops/kfp-caip-sklearn/lab-01-caip-containers/lab-01.ipynb

Instruction:
- Added the command to install gcsfs package.

Updated the notebook for lab-01

---

workshops/tfx-caip-tf23/lab-02-tfx-pipeline/labs/pipeline/pipeline.py
workshops/tfx-caip-tf23/lab-02-tfx-pipeline/solutions/pipeline/pipeline.py
workshops/tfx-caip-tf23/lab-03-tfx-cicd/labs/pipeline/pipeline.py
workshops/tfx-caip-tf23/lab-03-tfx-cicd/solutions/pipeline/pipeline.py
workshops/tfx-caip-tf23/lab-04-tfx-metadata/labs/pipeline/pipeline.py
workshops/tfx-caip-tf23/lab-04-tfx-metadata/solutions/pipeline/pipeline.py

- Update csvexamplegen to read output split config.

Fix TFX workshop csvexamplegen split configs.

---

on_demand/kfp-caip-sklearn/lab-01-caip-containers/exercises/lab-01.ipynb
on_demand/kfp-caip-sklearn/lab-01-caip-containers/lab-01.ipynb

- Updated gcsfs version in target and solution notebook
- Related buganizer: http://b/186189363

Update: lab-01.ipynb

---

workshops/kfp-caip-sklearn/lab-01-caip-containers/exercises/lab-01.ipynb
workshops/kfp-caip-sklearn/lab-01-caip-containers/lab-01.ipynb

- Updated gcsfs version in both target and solution notebook in workshop folder

Update: lab-01.ipynb notebook

---

on_demand/tfx-caip/install.sh
on_demand/tfx-caip/lab-02-tfx-pipeline/labs/lab-02.ipynb
on_demand/tfx-caip/lab-02-tfx-pipeline/labs/pipeline/config.py
on_demand/tfx-caip/lab-02-tfx-pipeline/labs/pipeline/features.py
on_demand/tfx-caip/lab-02-tfx-pipeline/labs/pipeline/model.py
on_demand/tfx-caip/lab-02-tfx-pipeline/labs/pipeline/pipeline.py
on_demand/tfx-caip/lab-02-tfx-pipeline/labs/pipeline/preprocessing.py
on_demand/tfx-caip/lab-02-tfx-pipeline/labs/pipeline/runner.py
on_demand/tfx-caip/lab-02-tfx-pipeline/solutions/lab-02.ipynb
on_demand/tfx-caip/lab-02-tfx-pipeline/solutions/pipeline/config.py
on_demand/tfx-caip/lab-02-tfx-pipeline/solutions/pipeline/features.py
on_demand/tfx-caip/lab-02-tfx-pipeline/solutions/pipeline/model.py
on_demand/tfx-caip/lab-02-tfx-pipeline/solutions/pipeline/pipeline.py
on_demand/tfx-caip/lab-02-tfx-pipeline/solutions/pipeline/preprocessing.py
on_demand/tfx-caip/lab-02-tfx-pipeline/solutions/pipeline/runner.py

- Reduce tuning, training, and tuning footprint for Qwiklabs constraints.
- Apply PEP8 formatting and linting enhancements.

Refactor TFX pipeline lab for on-demand courses.

---

on_demand/tfx-caip/lab-03-tfx-cicd/labs/pipeline/config.py
on_demand/tfx-caip/lab-03-tfx-cicd/labs/pipeline/features.py
on_demand/tfx-caip/lab-03-tfx-cicd/labs/pipeline/model.py
on_demand/tfx-caip/lab-03-tfx-cicd/labs/pipeline/pipeline.py
on_demand/tfx-caip/lab-03-tfx-cicd/labs/pipeline/preprocessing.py
on_demand/tfx-caip/lab-03-tfx-cicd/labs/pipeline/runner.py
on_demand/tfx-caip/lab-03-tfx-cicd/solutions/pipeline/config.py
on_demand/tfx-caip/lab-03-tfx-cicd/solutions/pipeline/features.py
on_demand/tfx-caip/lab-03-tfx-cicd/solutions/pipeline/model.py
on_demand/tfx-caip/lab-03-tfx-cicd/solutions/pipeline/pipeline.py
on_demand/tfx-caip/lab-03-tfx-cicd/solutions/pipeline/preprocessing.py
on_demand/tfx-caip/lab-03-tfx-cicd/solutions/pipeline/runner.py

- Update pipelines to reduce training, tuning, and resource footprint for Qwiklabs restrictions.
- Apply PEP8 formatting and linting enhancements.

Update lab 03 TFX CICD pipeline for on-demand

---

on_demand/tfx-caip/lab-04-tfx-metadata/labs/pipeline/config.py
on_demand/tfx-caip/lab-04-tfx-metadata/labs/pipeline/features.py
on_demand/tfx-caip/lab-04-tfx-metadata/labs/pipeline/model.py
on_demand/tfx-caip/lab-04-tfx-metadata/labs/pipeline/pipeline.py
on_demand/tfx-caip/lab-04-tfx-metadata/labs/pipeline/preprocessing.py
on_demand/tfx-caip/lab-04-tfx-metadata/labs/pipeline/runner.py
on_demand/tfx-caip/lab-04-tfx-metadata/solutions/pipeline/config.py
on_demand/tfx-caip/lab-04-tfx-metadata/solutions/pipeline/features.py
on_demand/tfx-caip/lab-04-tfx-metadata/solutions/pipeline/model.py
on_demand/tfx-caip/lab-04-tfx-metadata/solutions/pipeline/pipeline.py
on_demand/tfx-caip/lab-04-tfx-metadata/solutions/pipeline/preprocessing.py
on_demand/tfx-caip/lab-04-tfx-metadata/solutions/pipeline/runner.py

- Update pipeline to reduce training, tuning, and resource usage to conform with Qwiklabs restrictions.
- Apply PEP8 and linting formatting enhancements.

TFX lab 04 metadata updates for on-demand

---

immersion/kubeflow_pipelines/walkthrough/solutions/lab-01_vertex.ipynb

Now the first lab of the KFP immersion series trains, deploys, and tunes on Vertex AI. 
The best hyper-parameters are also retrieved programmatically from the Vertex platform. 
There should be no change to the training code itself nor its containerization. 
Only the platform code has been refactored.
Please test, and review.

Vertex refactor kfp lab 01 from immersion

---

on_demand/kfp-caip-sklearn/lab-02-kfp-pipeline/exercises/lab-02.ipynb

- Added the necessary instruction in the notebook as required.

Notebook_update: lab-02.ipynb [OCBL205]

---

immersion/kubeflow_pipelines/pipelines/labs/lab-02_vertex.ipynb
immersion/kubeflow_pipelines/pipelines/labs/pipeline_vertex/pipeline.py
immersion/kubeflow_pipelines/pipelines/labs/pipeline_vertex/training_lightweight_component.py
immersion/kubeflow_pipelines/pipelines/labs/pipeline_vertex/tuning_lightweight_component.py
immersion/kubeflow_pipelines/pipelines/labs/trainer_image_vertex/Dockerfile
immersion/kubeflow_pipelines/pipelines/labs/trainer_image_vertex/train.py

This PR adds the exercises to the vertex refactor of the [Kubeflow pipeline lab](https://github.com/GoogleCloudPlatform/mlops-on-gcp/blob/master/immersion/kubeflow_pipelines/pipelines/solutions/lab-02_vertex.ipynb) in the immersion series. 
I have tried to stay as close as possible to the original exercises that were covering the learning objectives.

Vertex refactor of the KFP lab 02 - Exercises

---

immersion/kubeflow_pipelines/walkthrough/labs/lab-01_vertex.ipynb

This PR adds exercises to the first KFP lab (walkthrough) from the immersion series. 
When possible I kept the same exercises as the original lab, since they covered the learning objectives.
I modified them to reflect the Vertex refactor.

Vertex refactor of the KFP lab 01 - Exercises

---

immersion/kubeflow_pipelines/cicd/labs/cloudbuild_vertex.yaml
immersion/kubeflow_pipelines/cicd/labs/kfp-cli_vertex/run_pipeline.py
immersion/kubeflow_pipelines/cicd/labs/lab-03_vertex.ipynb
immersion/kubeflow_pipelines/cicd/labs/pipeline_vertex/pipeline.py
immersion/kubeflow_pipelines/cicd/labs/pipeline_vertex/training_lightweight_component.py
immersion/kubeflow_pipelines/cicd/labs/pipeline_vertex/tuning_lightweight_component.py
immersion/kubeflow_pipelines/cicd/labs/trainer_image_vertex/Dockerfile
immersion/kubeflow_pipelines/cicd/labs/trainer_image_vertex/train.py

This PR adds the exercises to the vertex refactor of the Kubeflow ci/cd lab in the immersion series (lab 03).
I have tried to stay as close as possible to the original exercises that were covering the learning objectives.

Vertex refactor of the KFP lab 03 - Exercises

---

workshops/tfx-caip-tf23/lab-04-tfx-metadata/labs/lab-04.ipynb
workshops/tfx-caip-tf23/lab-04-tfx-metadata/solutions/lab-04.ipynb

- Updated the typo in target and solution notebook
- Related buganizer: http://b/227285241

Notebook Update: lab-04.ipynb

---

on_demand/kfp-caip-sklearn/lab-01-caip-containers/exercises/lab-01.ipynb
on_demand/kfp-caip-sklearn/lab-01-caip-containers/lab-01.ipynb

- Updated dataset path in `Target` and `Solution` file
- Buganizer: http://b/235582892

Update Notebook: OCBL203 Using custom containers with AI Platform Training

---

workshops/tfx-caip-tf23/lab-01-tfx-walkthrough/labs/lab-01.ipynb
workshops/tfx-caip-tf23/lab-01-tfx-walkthrough/solutions/lab-01.ipynb

- Updated the DATA_ROOT path with “gs://cloud-training/OCBL203/workshop-datasets” in the target and solution notebook both.
- Updated the target and solution notebook instructions as necessary.
- Added the note to restart the kernel.
- Updated the content formatting of the instructions.
- Reference buganizer: http://b/242099550

OCBL215 - TFX Standard Components Walkthrough

---

immersion/kubeflow_pipelines/walkthrough/labs/lab-01_vertex.ipynb
immersion/kubeflow_pipelines/walkthrough/solutions/lab-01_vertex.ipynb

- Added the instructions.
- Updated the cells as required.
- Updated the cell outputs as required.
- Buganizer: http://b/261553100

Notebook_update: lab-01_vertex.ipynb

---

workshops/tfx-caip-tf23/lab-02-tfx-pipeline/labs/lab-02.ipynb
workshops/tfx-caip-tf23/lab-02-tfx-pipeline/solutions/lab-02.ipynb

- Removed the cells of the optional part
- Reference Buganizer: http://b/302087094

Removed the optional part
